# Generated by Django 2.2.5 on 2019-09-09 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('roll_no', models.BigIntegerField()),
                ('gender', models.CharField(max_length=8)),
                ('department', models.CharField(max_length=4)),
                ('register_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
