# Generated by Django 2.2.5 on 2019-09-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='_classes',
            new_name='classes',
        ),
    ]
