# Generated by Django 2.2.5 on 2019-09-11 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_auto_20190911_0020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
