# Generated by Django 2.2.5 on 2019-09-12 22:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_auto_20190912_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('subject', models.CharField(max_length=20)),
                ('taken_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_app.Staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_app.Student')),
            ],
        ),
    ]
