# Generated by Django 2.2.5 on 2019-09-11 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0003_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=8)),
                ('department', models.CharField(max_length=4)),
                ('register_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
