# Generated by Django 2.2.5 on 2019-09-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='_class',
            field=models.CharField(default='be4', max_length=5),
            preserve_default=False,
        ),
    ]
