# Generated by Django 2.2.5 on 2019-09-11 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_auto_20190911_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='coordinator',
            field=models.ForeignKey(default='Ranjeet Bidwe', on_delete=django.db.models.deletion.DO_NOTHING, to='student_app.Staff'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.Department'),
        ),
    ]
