# Generated by Django 2.2.5 on 2019-09-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='_class',
            new_name='class_obj',
        ),
    ]
