# Generated by Django 2.2.5 on 2019-09-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_auto_20190911_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='_class',
        ),
    ]
