# Generated by Django 2.2.5 on 2019-09-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0009_exam'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('name', 'student')},
        ),
    ]
