# Generated by Django 2.2.5 on 2019-09-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0010_auto_20190914_0042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set(),
        ),
    ]
