# Generated by Django 2.2.5 on 2019-09-13 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0012_book_borrowrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='copies',
        ),
    ]
