# Generated by Django 2.2.5 on 2019-09-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0014_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
