# Generated by Django 2.2.5 on 2019-09-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0015_auto_20190914_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_pic',
        ),
    ]
