# Generated by Django 2.2.5 on 2019-09-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0016_remove_student_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobile_no',
            field=models.IntegerField(default=9876543210),
            preserve_default=False,
        ),
    ]
