# Generated by Django 2.2.5 on 2019-09-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0017_student_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile_no',
            field=models.IntegerField(default=9876543210),
        ),
    ]
